export const techStack = [
  {label: 'Next.js', value: 'nextjs'},
  {label: 'React', value: 'react'},
  {label: 'JavaScript', value: 'javascript'},
  {label: 'TypeScript', value: 'typescript'},
  {label: 'TailwindCSS', value: 'tailwindcss'},
  {label: 'CSS', value: 'css'},
  {label: 'HTML', value: 'html'},
  {label: 'Git', value: 'git'},
  {label: 'Node.js', value: 'nodejs'},
  {label: 'Express.js', value: 'expressjs'},
  {label: 'MongoDB', value: 'mongodb'},
  {label: 'React Query', value: 'react-query'},
  {label: 'tRPC', value: 'trpc'},
  {label: 'Sanity', value: 'sanity'},
  {label: 'SendGrid', value: 'sendgrid'},
  {label: 'Prisma', value: 'prisma'},
  {label: 'Sentry', value: 'sentry'},
  {label: 'Playwright', value: 'playwright'},
  {label: 'Mixpanel', value: 'mixpanel'},
  {label: 'OpenAI', value: 'openai'},
  {label: 'Express.js', value: 'expressjs'},
  {label: 'NestJS', value: 'nestjs'},
  {label: 'Node.js', value: 'nodejs'},
  {label: 'DigitalOcean', value: 'digitalocean'},
  {label: 'Career', value: 'career'},
  {label: 'Personal', value: 'personal'},
]
