# fly.toml app configuration file generated for sanity-blog on 2023-06-05T15:02:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sanity-blog"
primary_region = "yyz"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
